# Generated by Django 4.2.1 on 2023-05-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(default="aa", max_length=2)),
                (
                    "massage",
                    models.TextField(
                        default="If u eant the job please call 010022", max_length=100
                    ),
                ),
            ],
        ),
    ]
