# Generated by Django 4.2.1 on 2023-05-04 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="job", old_name="massage", new_name="order",),
    ]
