# Generated by Django 4.1.1 on 2023-05-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='rr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
