# Generated by Django 4.1.1 on 2023-05-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_job_rr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='rr',
        ),
        migrations.AddField(
            model_name='chat',
            name='rr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
