# Generated by Django 4.1.1 on 2023-05-07 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_job_rr_chat_rr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='rr',
        ),
    ]
