# Generated by Django 4.1.1 on 2023-05-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_chat_server_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
