# Generated by Django 4.1.1 on 2023-05-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_job_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='server_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='order',
            field=models.TextField(blank=True, null=True),
        ),
    ]
