# Generated by Django 4.1.1 on 2023-05-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_chat_message_alter_chat_server_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='perant_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
