# Generated by Django 4.1.1 on 2023-05-19 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_new_static_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_static_message',
            old_name='perant_id',
            new_name='perant',
        ),
    ]
