# Generated by Django 4.1.1 on 2023-05-19 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_rename_perant_id_new_static_message_perant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_static_message',
            old_name='perant',
            new_name='parent',
        ),
    ]
